# IAM Policies - Generated by IAM Analyzer
# Generated: 2025-07-22 23:06:56
# Removed 20 unused permissions

resource "aws_iam_user_policy" "alice-analyst-test_policy" {
  name = "alice-analyst-test-policy"
  user = aws_iam_user.alice_analyst_test.name

  # Optimized policy - removed 10 unused permissions
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "MinimalRequiredAccess"
        Effect = "Allow"
        Action = [
          "s3:GetObject",
          "s3:ListBucket",
          "athena:StartQueryExecution", 
          "athena:GetQueryResults",
          "cloudwatch:PutMetricData",
          "kms:Decrypt"
        ]
        Resource = "*"
      }
    ]
  })
}

resource "aws_iam_user_policy" "bob-dev-test_policy" {
  name = "bob-dev-test-policy"
  user = aws_iam_user.bob_dev_test.name

  # Optimized policy - removed 8 unused permissions
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "MinimalRequiredAccess"
        Effect = "Allow"
        Action = [
          "s3:GetObject",
          "s3:ListBucket",
          "athena:StartQueryExecution", 
          "athena:GetQueryResults",
          "cloudwatch:PutMetricData",
          "kms:Decrypt"
        ]
        Resource = "*"
      }
    ]
  })
}

resource "aws_iam_user_policy" "dave-observer-test_policy" {
  name = "dave-observer-test-policy"
  user = aws_iam_user.dave_observer_test.name

  # Optimized policy - removed 2 unused permissions
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "MinimalRequiredAccess"
        Effect = "Allow"
        Action = [
          "s3:GetObject",
          "s3:ListBucket",
          "athena:StartQueryExecution", 
          "athena:GetQueryResults",
          "cloudwatch:PutMetricData",
          "kms:Decrypt"
        ]
        Resource = "*"
      }
    ]
  })
}

