# Generated by Least Privilege Optimizer - 2025-06-23 00:47:27
# Access Analyzer Finding: 88169d3f-40b1-4148-92c3-dd74d76f78c9
# Resource: alice-analyst-test
# Recommendation Type: remove_unused_permissions
#
# This file contains AWS Access Analyzer recommendations for least privilege access.
# Review the recommendations and apply them after thorough testing.

# RECOMMENDATION: Remove Unused Permissions
# This resource has 9 unused AWS service namespaces
# Total unused actions detected: 23
#
# Unused Services: athena, cloudwatch, dynamodb, glue, iam, kms, lambda, s3, sts
#
# VALIDATION: All recommendations validated with AWS Access Analyzer validate-policy API
#
# INSTRUCTIONS:
# 1. Review the unused services and actions below
# 2. Remove these permissions from your IAM policies
# 3. Test thoroughly in a non-production environment
# 4. Apply changes gradually with monitoring

# Unused Actions by Service:
#
# ATHENA Service (1 actions):
#   - athena:*
#
# CLOUDWATCH Service (1 actions):
#   - cloudwatch:*
#
# DYNAMODB Service (1 actions):
#   - dynamodb:*
#
# GLUE Service (1 actions):
#   - glue:*
#
# IAM Service (6 actions):
#   - iam:*
#   - iam:PassRole
#   - iam:CreateRole
#   - iam:AttachRolePolicy
#   - iam:DetachRolePolicy
#   - iam:DeleteRole
#
# KMS Service (1 actions):
#   - kms:*
#
# LAMBDA Service (5 actions):
#   - lambda:*
#   - lambda:CreateFunction
#   - lambda:InvokeFunction
#   - lambda:UpdateFunctionCode
#   - lambda:DeleteFunction
#
# S3 Service (6 actions):
#   - s3:*
#   - s3:GetObject
#   - s3:PutObject
#   - s3:DeleteObject
#   - s3:ListBucket
#   - s3:GetBucketLocation
#
# STS Service (1 actions):
#   - sts:*
