# Generated by Least Privilege Optimizer - 2025-06-23 00:44:45
# Access Analyzer Finding: b18bd454-3888-4471-8dba-8d02302ad998
# Resource: bob-dev-test
# Recommendation Type: remove_unused_permissions
#
# This file contains AWS Access Analyzer recommendations for least privilege access.
# Review the recommendations and apply them after thorough testing.

# RECOMMENDATION: Remove Unused Permissions
# This resource has 6 unused AWS service namespaces
# Total unused actions detected: 33
#
# Unused Services: ecr, ecs, iam, lambda, logs, s3
#
# VALIDATION: All recommendations validated with AWS Access Analyzer validate-policy API
#
# INSTRUCTIONS:
# 1. Review the unused services and actions below
# 2. Remove these permissions from your IAM policies
# 3. Test thoroughly in a non-production environment
# 4. Apply changes gradually with monitoring

# Unused Actions by Service:
#
# ECR Service (5 actions):
#   - ecr:*
#   - ecr:GetAuthorizationToken
#   - ecr:BatchCheckLayerAvailability
#   - ecr:GetDownloadUrlForLayer
#   - ecr:BatchGetImage
#
# ECS Service (6 actions):
#   - ecs:*
#   - ecs:CreateCluster
#   - ecs:DescribeClusters
#   - ecs:RunTask
#   - ecs:StopTask
#   - ecs:DescribeTasks
#
# IAM Service (6 actions):
#   - iam:*
#   - iam:PassRole
#   - iam:CreateRole
#   - iam:AttachRolePolicy
#   - iam:DetachRolePolicy
#   - iam:DeleteRole
#
# LAMBDA Service (5 actions):
#   - lambda:*
#   - lambda:CreateFunction
#   - lambda:InvokeFunction
#   - lambda:UpdateFunctionCode
#   - lambda:DeleteFunction
#
# LOGS Service (5 actions):
#   - logs:*
#   - logs:CreateLogGroup
#   - logs:CreateLogStream
#   - logs:PutLogEvents
#   - logs:DescribeLogGroups
#
# S3 Service (6 actions):
#   - s3:*
#   - s3:GetObject
#   - s3:PutObject
#   - s3:DeleteObject
#   - s3:ListBucket
#   - s3:GetBucketLocation
