# Generated by Least Privilege Optimizer - 2025-06-23 01:33:20
# Access Analyzer Finding: ff720836-1d0c-4551-86a6-88d758993273
# Resource: dave-observer-test
# Recommendation Type: remove_unused_permissions
#
# This file contains AWS Access Analyzer recommendations for least privilege access.
# Review the recommendations and apply them after thorough testing.

# RECOMMENDATION: Remove Unused Permissions
# This resource has 4 unused AWS service namespaces
# Total unused actions detected: 13
#
# Unused Services: cloudwatch, glue, logs, s3
#
# VALIDATION: All recommendations validated with AWS Access Analyzer validate-policy API
#
# INSTRUCTIONS:
# 1. Review the unused services and actions below
# 2. Remove these permissions from your IAM policies
# 3. Test thoroughly in a non-production environment
# 4. Apply changes gradually with monitoring

# Unused Actions by Service:
#
# CLOUDWATCH Service (1 actions):
#   - cloudwatch:*
#
# GLUE Service (1 actions):
#   - glue:*
#
# LOGS Service (5 actions):
#   - logs:*
#   - logs:CreateLogGroup
#   - logs:CreateLogStream
#   - logs:PutLogEvents
#   - logs:DescribeLogGroups
#
# S3 Service (6 actions):
#   - s3:*
#   - s3:GetObject
#   - s3:PutObject
#   - s3:DeleteObject
#   - s3:ListBucket
#   - s3:GetBucketLocation
